language: python
python: '3.6'
branches:
  only:  # можно перечислить ветки из которых должен быть автоматический запуск сборки на каждый push кода в репозиторий
  - master
  - develop
install:  # раздел предварительной настройки окружения до сборки
  - pip install pytest coverage codacy-coverage  # эти библиотеки используются для запуска юнит-тестов сбора статистики покрытия кода юнит-тестами для сервиса Codacy
script:  # основной шаг сборки, состоящий из последовательного запуска скриптов
  - printenv  # для отладки очень помогает вывод переменных окружения в логах Travis CI, потом этот шаг можно удалить
  - ls -la  # также для отладки, потом этот шаг можно удалить
  - coverage run -m py.test tests  # собираем покрытие кода тестами
  - coverage xml  # формируем отчёт для Codacy
  - python-codacy-coverage -r coverage.xml  # аплоадим отчёт в Codacy
deploy:  # раздел деплоя в котором можно указать действия, которые нужно произвести с успешно собранным артефактом
  provider: pypi  # например, Travis CI поддерживает автоматическую загрузку в PyPI через указание провайдера "pypi"
  user: devopshq  # логин проекта в PyPI
  password:  # зашифрованный пароль для PyPI через утилиту travis-encrypt подставьте в переменную secure ниже:
    secure: "M3Lb3KyUmvph+uRhMOU3VQg2FPtTJB0bCoTt7uTVNoDkvndyqYMAkwLoFnroiHOXs+ibc68TabZJWwwzdmSl4z98hyqZTlgz4O6gZpsPttR7wP7CNvrlDQ5e6//4VD8hUrQJJBGQVoBiyzoOobD/JcKJN7FwjlcI+Cug73STD9a3ePUU0TUPkdvXhG7eUJXD2Dr5VMmvg9HfjO1L0Zs05gaKWK5o9gILkSZEVNicCc5b8/qlBIpaEak0PoLV4cn1AB7bX2pAgBpPkEahcf3ox1jwdAb+WUPiauxr2mInhvUuJNib6I5wyMtjmcQeZIu+bWhyTVr6R6JqfBjwk2mgsGgbayPVR5SW6B40pT57BlNreTvteTtaUa2xncrvkTBjCWpDVdTP2i8r16U6qrt6txPiJ8IsYlnDmVNYCEoxPBRwKRNyr/9lEI2OHmsZNQ/eNxKCfSwk/aNYAdzEQA5+QyFTep9mCDv8HcrmFUkPwWQIAReBhRSLIktTkVXhfN4H3DrybEJ928M/vGCeiSJmK+1XLlnQJmz6SlSAgSW02O7UWsan4d603zFJGB3Bz/n/rbd+YcFCysi3T4+bwLxpqX9vkLAR3eFR50i4fdnU3Op3KI4ri3zQLdE+YRewnywQ/B8sPvqHhAuhtUPl2R6t9JJOAiR8BgqLd0K7ziodtG0="
  distributions: sdist bdist_wheel  # виды артефактов, которые нужно загрузить в PyPY, sdist загружает .tar.gz, bdist_wheel - загружает wheel-файл
  on:
    all_branches: true
  skip_cleanup: true
after_script:  # команды которые нужно выполнить после успешного окончания сборки и деплоя
  - echo "Deploy to PyPI finished."
env:
  global:  # здесь можно разместить общие переменные и секреты доступные для всех шагов сборки. Например, секрет для Codacy, зашифрованный через утилиту travis-encrypt подставьте в переменную secure ниже:
  - secure: "Uv8cJkAppkaSbmi9Vnk2FXKAXS3juK6lkDRd0py72vnB4/JNV2ISIOeV4NruMq8aYl5d2T8bDve3PqUOdVCGtx9xyj1eHxaND7oaNUs2b3klstf9rXyzlrhA4VdmPJH1S9iX1ipJkwOwWs9yV+DaZJjcG5QMBZiPomwJg0kTfaJVaPdyxpyDP7urS0NJZ39AvEs5KW9maSOz4wExBOCZiZO4tn/svcZa0yJDyeEUrbJNKJBa/5i9KEE8NgXGUW7Je6m4T32oZR+2g1/D/ENnHg+Hed/ICYt7dQ9RcgfxXDrS/bY9mVJfe8ZxLEiiYuANJTxZ+s5Uh/ctGj01eO5y8li6u5EyYuVxZzb3GVbvGOb3ca9EULzHov9DLrMkIt40PCr0VDAyTvpN5LF0XOrAG3U7GWcb7hEXGtTIMXwZzAHEaVfDR7Wxv9JXKrz2WZ8uLdPqE6gi+qEu/15MzbOKeMIcU34XZEuO5FpS1QCWHnl3cGbyWP7en/dBwcmSoFCUF4PGTzL4NyYNEBCgx3mRzzoaKgWbuEjJDCyEvZTNcPlGGunzAv1wNwnBJoH+N+AI1T5SHWOHHlKT0d/BWh37VNtIG4y+Q1Q6sj6LKkIlaW2agp7oylBHj7aRxHHKdEgqERdwbNfWVKjoLz7FfMDrbAaJc6sMsdMNldfE57GXXGU="
